### ISSUE TITLE
Priming can format cache

### ISSUE THREAD

**Issue by jasonjoneski** [dprint/dprint-intellij#88]
When I enable the d-print plugin, it get's stuck in a loop of background tasks in IntelliJ.

It will run `Initialising editor service` followed by a `Priming can format cache for $file` for each file in my project.  I would expect this to run once, but it happens continuously in a loop. When I uncheck `Enable dprint` in the settings, this goes away.

Here is a screen capture of the output in my Background Tasks:

![image](https://github.com/dprint/dprint-intellij/assets/5563726/48300a07-078b-4f8e-a24f-0e93edac56ba)

I have 
**IntelliJ IDEA 2024.1.3 (Ultimate Edition)**
Build #IU-241.17890.1, built on June 3, 2024

Dprint plugin: 0.6.0

**Comment by ryan-rushton** [comment]
Thanks for the report. It should prime the formatting cache for each open file on startup due to some issues with how IntelliJ isn't great at allowing outside processes to run in the formatting pipeline. 

The fact that it is getting stuck in a loop is definitely weird. It should try to restart once and abort if it fails. I will look into it.
